amcl:
  ros__parameters:
    use_map_topic: true
    first_map_only: false
    update_min_d: 0.2
    update_min_a: 0.2
    kld_err: 0.05
    kld_z: 0.99
    scan_topic: scan
    min_particles: 500
    max_particles: 2000
    tf_broadcast: true
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    resample_interval: 2
    laser_min_range: -1.0
    laser_max_range: -1.0
    laser_max_beams: 30
    laser_z_hit: 0.95
    laser_z_short: 0.1
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    odom_alpha5: 0.1
    odom_model_type: diff
    gui_publish_rate: 10.0
    save_pose_rate: 0.5
